def utils

pipeline {
    agent {
        label "$agent"
    }
    tools {
        nodejs "NODE22"
        maven "MVN39"
        jdk "JDK21"
    }
    options {
        withFolderProperties()
        skipDefaultCheckout(true)
    }
    environment {
        def SCRIPTS_DIR="toto-jenkins/scripts"
        def GROOVY_DIR="${SCRIPTS_DIR}/groovy"
        def SH_DIR="${SCRIPTS_DIR}/sh"
    }
    stages {
        stage("Before prepare")  {
            steps {
                script {
                    if(params.event != "push") {
                        currentBuild.result = "ABORTED"
                        error("Expected 'push' event, was '" + params.event + "'")
                    }
                    cleanWs()
                    checkout(scm)
                    utils = load("${GROOVY_DIR}/utils.groovy")
                    utils.printParams(params)
                }
            }
        }
        stage("Prepare integration tests") {
            when{
                expression { return !params.skip_test }
            }
            environment {
                DB_ADMIN = credentials("redwood-db-admin-user")
            }
            steps {
                script {
                    utils.handleStage({
                        configFileProvider(
                            [configFile(fileId: 'toto-business-test-env', variable: 'TEST_ENV_FILE_PATH')]) {
                                utils.bash('$SH_DIR/prepare-integration-tests.sh', env.TEST_ENV_FILE_PATH, env.DB_ADMIN_USR, env.DB_ADMIN_PSW, 'redwood', 'toto_test')
                        }
                    }, { msg -> unstable(msg) })
                }
            }
        }
        stage("Prepare business artifacts") {
            steps {
                script {
                    utils.handleStage({
                        configFileProvider(
                            [configFile(fileId: 'toto-business-env', variable: 'ENV_FILE_PATH')]) {
                                utils.bash('$SH_DIR/prepare-business.sh', env.ENV_FILE_PATH, "${params.skip_test}")
                        }
                    }, { msg -> unstable(msg) })
                }
            }
            post {
                always {
                    junit(
                        allowEmptyResults: true,
                        testResults: '**/surefire-reports/*.xml'
                    )
                    recordCoverage(
                        tools: [[parser: 'JACOCO']],
                        id: 'jacoco', name: 'JaCoCo Coverage',
                        sourceDirectories: [[path:'	toto-business/src/main/java']],
                        sourceCodeRetention: 'EVERY_BUILD',
                        qualityGates: [
                                [threshold: 60.0, metric: 'LINE', baseline: 'PROJECT', unstable: true],
                                [threshold: 60.0, metric: 'BRANCH', baseline: 'PROJECT', unstable: true]]
                    )
                }
            }
        }
        stage("Prepare presentation artifacts") {
            steps {
                script {
                    utils.handleStage({
                        configFileProvider(
                            [configFile(fileId: 'toto-presentation-env', variable: 'ENV_FILE_PATH')]) {
                                utils.bash('$SH_DIR/prepare-presentation.sh', env.ENV_FILE_PATH)
                        }
                    }, { msg -> unstable(msg) })
                }
            }
        }
        stage("Before deploy") { // Checks if build is unstable, if so then fail
            steps {
                script {
                    if(utils.jobIsUnstable()) {
                        error("Skipping deployment stages, at least one of prepare stages is unstable")
                    }
                }
            }
        }
        stage("Deploy data") {
            environment {
                DB_ADMIN = credentials("redwood-db-admin-user")
            }
            steps {
                script {
                    utils.handleStage({
                        utils.bash('$SH_DIR/deploy-data.sh', env.TOTO_DATA_DEPLOY_DIR, env.DB_ADMIN_USR, env.DB_ADMIN_PSW, 'redwood', 'toto_app')
                    })
                }
            }
        }
        stage("Deploy business") {
            steps {
                script {
                    utils.handleStage({
                        utils.bash('$SH_DIR/deploy-business.sh', env.TOTO_BUSINESS_DEPLOY_DIR, env.TOTO_BUSINESS_URL, env.TOTO_BUSINESS_PORT)
                    })
                }
            }
        }
        stage("Deploy presentation") {
            steps {
                script {
                    utils.handleStage({
                        utils.bash('$SH_DIR/deploy-presentation.sh', env.TOTO_PRESENTATION_DEPLOY_DIR, env.TOTO_PRESENTATION_URL)
                    })
                }
            }
        }
    }
    post {
        always {
            script {
                if(params.report) {
                    echo "Sending report..."
                    mail(to: "${MAIL_TO}", subject: "[JENKINS] - ${env.JOB_BASE_NAME} #${env.BUILD_ID} - ${currentBuild.currentResult} ", body: "${env.BUILD_URL}")
                } else {
                    echo "Report disabled, not sending report"
                }
            }
        }
    }
}
