pipeline {
    agent {
        label "$NODE"
    }
    tools {
        nodejs "NODE22"
    }
    stages {
        stage("Pre stage")  {
            steps {
                script {
                    if(params.event != "push") {
                        currentBuild.result = "ABORTED"
                        error("Must be a push event, was: " + params.event)
                    }
                }
            }
        }
        stage("Build presentation") {
            steps {
                sh('node -v')
                sh('npm -v')
                echo "${NODE}"
                echo "${params.event}"
                echo "${params.delivery}"
                echo "${params.hook}"
                echo "${params.trigger}"
            }
        }
    }
}