pipeline {
    agent {
        label "$NODE"
    }
    tools {
        nodejs "NODE22"
    }
    stages {
        stage("Build presentation") {
            steps {
                sh('node -v')
                sh('npm -v')
                echo "${NODE}"
                echo "${params.event}"
                echo "${params.delivery}"
                echo "${params.hook}"
                echo "${params.trigger}"
            }
        }
    }
}